<a href="https://colab.research.google.com/github/kowalsp/data_science/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('ala ma kota')

ala ma kota


In [3]:
import numpy as np
np.__version__

'1.23.5'

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [9]:
x = np.array([1,3])
print(x)

[1 3]


In [10]:
x.shape

(2,)

In [11]:
x.dtype

dtype('int64')

In [12]:
x.ndim

1

In [13]:
y = np.array([[1,2,3],[2,4,6]])

In [14]:
y.shape

(2, 3)

In [16]:
z = np.array([[[1,2,3],[1,1,1],
              [1,2,3],[2,2,2]],

              [[2,3,4],[1,1,1],
               [2,3,4],[2,2,2]],

              [[3,4,5],[1,1,1],
               [3,4,5],[2,2,2]]])

In [17]:
z.ndim

3

In [18]:
z.shape

(3, 4, 3)

In [19]:
np.zeros(shape=(4,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones(shape = (10,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full(shape=(3,3), fill_value=5, dtype=int )

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [26]:
np.arange(start=10, stop = 50, step = 2, dtype=int)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [27]:
np.linspace(start=10, stop=20, num=11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [29]:
A = np.arange(15)

In [30]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
A = np.array([1,2,3,4])
B = np.array([3,4,5,6])

In [34]:
A
B

array([3, 4, 5, 6])

In [35]:
A + B

array([ 4,  6,  8, 10])

In [36]:
A - B

array([-2, -2, -2, -2])

In [37]:
A * B

array([ 3,  8, 15, 24])

In [38]:
A /B

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [39]:
A + 2

array([3, 4, 5, 6])

In [40]:
A * 3

array([ 3,  6,  9, 12])

In [41]:
np.add(A,B)

array([ 4,  6,  8, 10])

In [42]:
X = np.array([[1,2],[2,3]])
Y = np.array([[3,4],[5,6]])

In [43]:
X * Y

array([[ 3,  8],
       [10, 18]])

In [44]:
X @ Y

array([[13, 16],
       [21, 26]])

In [45]:
np.dot(X,Y)

array([[13, 16],
       [21, 26]])

In [46]:
X.dot(Y)

array([[13, 16],
       [21, 26]])

In [47]:
Y.dot(X)

array([[11, 18],
       [17, 28]])

In [5]:
import numpy as np

In [6]:
np.random.rand(10,2)

array([[0.0483929 , 0.43789624],
       [0.19877527, 0.88675864],
       [0.00726589, 0.54154906],
       [0.36291799, 0.12718002],
       [0.60335717, 0.3747309 ],
       [0.98438288, 0.1651848 ],
       [0.69513294, 0.8496704 ],
       [0.83335372, 0.71547265],
       [0.73106353, 0.43763873],
       [0.94517059, 0.16485865]])

In [7]:
np.random.randint(10)

8

In [9]:
np.random.randint(low=10, high = 101, size = 20 )

array([ 77,  97,  81,  91,  53,  51,  87,  44,  23,  96,  89,  25,  60,
        53,  91,  46,  19, 100,  21,  13])

In [10]:
np.random.choice([2,4,6,7])

6

In [20]:
np.random.choice(['aaa','bbb','ccc'])

'ccc'

In [22]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
A[2:6]

array([2, 3, 4, 5])

In [26]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
A[:,-1]

array([ 4,  9, 14, 19])

In [31]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [34]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [35]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [36]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [41]:
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [42]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [44]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])