<a href="https://colab.research.google.com/github/kowalsp/data_science/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [ ]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [ ]:
X = A_inv@B
X

array([[1.],
       [2.]])

In [ ]:
Y = np.dot(A_inv,B)
Y

array([[1.],
       [2.]])

In [2]:
import numpy as np

In [3]:
price = np.array([[12.4,12.8,11.9,1000],[12.5,13.0,11.7,2000],[12.2,13.4,12.2,1500]])
price

array([[  12.4,   12.8,   11.9, 1000. ],
       [  12.5,   13. ,   11.7, 2000. ],
       [  12.2,   13.4,   12.2, 1500. ]])

In [5]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8, 4500. ])

In [6]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7, 1000. ])

In [7]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2, 2000. ])

In [9]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333, 1500.        ])

In [10]:
np.median(price, axis=0)

array([  12.4,   13. ,   11.9, 1500. ])

In [11]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.08248290e+02])

In [12]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.66666667e+05])