<a href="https://colab.research.google.com/github/kowalsp/data_science/blob/main/01_wprowadzenie/02_algebra_liniowa_skrocona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [ ]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [ ]:
X = A_inv@B
X

array([[1.],
       [2.]])

In [ ]:
Y = np.dot(A_inv,B)
Y

array([[1.],
       [2.]])